services:
  fhirflare:
    image: ${FHIRFLARE_IMAGE:-ghcr.io/sudo-jhare/fhirflare-ig-toolkit-lite:latest}
    ports:
      - "5000:5000"
    # Ephemeral Docker named volumes for all data storage. No data is stored on the host filesystem.
    volumes:
      - fhirflare-instance:/app/instance
      - fhirflare-uploads:/app/static/uploads
      - fhirflare-h2-data:/app/h2-data
      - fhirflare-logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - NODE_PATH=/usr/lib/node_modules
      - APP_MODE=lite
      - APP_BASE_URL=http://localhost:5000
      - HAPI_FHIR_URL=https://cdr.fhirlab.net/fhir
    command: supervisord -c /etc/supervisord.conf

volumes:
  fhirflare-instance:
  fhirflare-uploads:
  fhirflare-h2-data:
  fhirflare-logs: