{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fhirflare-ig-toolkit.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "fhirflare-ig-toolkit.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
        {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ .Values.service.port | default 5000 }}
        {{- else }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ .Values.service.port | default 5000 }}
        {{- end }}
{{- end }}