# This docker-compose file uses ephemeral Docker named volumes for all data storage.
# These volumes persist only as long as the Docker volumes exist and are deleted if you run `docker-compose down -v`.
# No data is stored on the host filesystem. If you want persistent storage, replace these with host mounts.
services:
  fhirflare-standalone:
    image: ${FHIRFLARE_IMAGE:-ghcr.io/sudo-jhare/fhirflare-ig-toolkit-standalone:latest}
    container_name: fhirflare-standalone
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - fhirflare-instance:/app/instance
      - fhirflare-uploads:/app/static/uploads
      - fhirflare-h2-data:/app/h2-data
      - fhirflare-logs:/app/logs
    restart: unless-stopped

volumes:
  fhirflare-instance:
  fhirflare-uploads:
  fhirflare-h2-data:
  fhirflare-logs: