"""Add must_support_elements_json to ProcessedIg

Revision ID: 5e6021b572ee
Revises: 8809253da459
Create Date: 2025-04-08 11:41:38.532125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6021b572ee'
down_revision = '8809253da459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_ig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_support_elements_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_ig', schema=None) as batch_op:
        batch_op.drop_column('must_support_elements_json')

    # ### end Alembic commands ###
