"""Rename resource_types_json to resource_types_info_json in ProcessedIg

Revision ID: 8809253da459
Revises: 7d0cdff4c7ad
Create Date: 2025-04-08 09:20:55.669990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8809253da459'
down_revision = '7d0cdff4c7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_ig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_types_info_json', sa.Text(), nullable=True))
        batch_op.drop_column('resource_types_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_ig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_types_json', sa.TEXT(), nullable=True))
        batch_op.drop_column('resource_types_info_json')

    # ### end Alembic commands ###
