"""Add examples_json to ProcessedIg

Revision ID: d8f620f74fbe
Revises: 5e6021b572ee
Create Date: 2025-04-08 12:45:21.475913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f620f74fbe'
down_revision = '5e6021b572ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_ig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examples_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_ig', schema=None) as batch_op:
        batch_op.drop_column('examples_json')

    # ### end Alembic commands ###
