hapi.fhir:
  ig_runtime_upload_enabled: false
  narrative_enabled: true
  logical_urls:
    - http://terminology.hl7.org/*
    - https://terminology.hl7.org/*
    - http://snomed.info/*
    - https://snomed.info/*
    - http://unitsofmeasure.org/*
    - https://unitsofmeasure.org/*
    - http://loinc.org/*
    - https://loinc.org/*
  cors:
    allow_Credentials: true
    allowed_origin:
      - '*'
  tester.home.name: FHIRFLARE Tester
  inline_resource_storage_below_size: 4000
