services:
  fhirflare:
    image: ${FHIRFLARE_IMAGE:-ghcr.io/sudo-jhare/fhirflare-ig-toolkit-lite:latest}
    ports:
      - "5000:5000"
    # Ephemeral Docker named volumes for all data storage. No data is stored on the host filesystem.
    volumes:
      - fhirflare-instance:/app/instance
      - fhirflare-uploads:/app/static/uploads
      - fhirflare-h2-data:/app/h2-data
      - fhirflare-logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - NODE_PATH=/usr/lib/node_modules
      - APP_MODE=lite
      - APP_BASE_URL=http://localhost:5000
      - HAPI_FHIR_URL=http://fhir:8080/fhir
    command: supervisord -c /etc/supervisord.conf

  fhir:
    container_name: hapi
    image: "hapiproject/hapi:v8.2.0-1"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db

  db:
    image: "postgres:17.2-bookworm"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data

configs:
  hapi:
     file: ./application.yaml

volumes:
  fhirflare-instance:
  fhirflare-uploads:
  fhirflare-h2-data:
  fhirflare-logs: